Drop Autotools
Begone, evil.

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -16,70 +16,6 @@ on:
     - main
 
 jobs:
-  check:
-    name: Build with Autotools and gcc, and test
-    runs-on: ubuntu-22.04
-    steps:
-    - name: Install Dependencies
-      run: |
-        sudo apt-get update
-        sudo apt-get install -y \
-          autoconf \
-          autoconf-archive \
-          automake \
-          autopoint \
-          clang \
-          dbus \
-          docbook-xml \
-          docbook-xsl \
-          libglib2.0-dev \
-          libtool \
-          xsltproc \
-          ${NULL+}
-    - name: Check out xdg-dbus-proxy
-      uses: actions/checkout@v1
-      with:
-        submodules: true
-    - name: Create logs dir
-      run: mkdir test-logs
-    - name: autoreconf
-      run: autoreconf -fi
-    - name: configure
-      run: |
-        mkdir _build
-        ( cd _build && ../configure --enable-man )
-      env:
-        CFLAGS: >-
-          -O2
-          -Wp,-D_FORTIFY_SOURCE=2
-          -fsanitize=address
-          -fsanitize=undefined
-    - name: Build xdg-dbus-proxy
-      run: make -C _build -j $(getconf _NPROCESSORS_ONLN) V=1
-    - name: Run tests
-      run: make -C _build -j $(getconf _NPROCESSORS_ONLN) check VERBOSE=1
-    - name: Run tests
-      run: make -C _build -j $(getconf _NPROCESSORS_ONLN) check VERBOSE=1
-    - name: Collect overall test logs on failure
-      if: failure()
-      run: mv _build/test-suite.log test-logs/ || true
-    - name: Collect individual test logs on cancel
-      if: failure() || cancelled()
-      run: mv _build/tests/*.log test-logs/ || true
-    - name: Upload test logs
-      uses: actions/upload-artifact@v1
-      if: failure() || cancelled()
-      with:
-        name: test logs
-        path: test-logs
-    - name: install
-      run: |
-        make -C _build install DESTDIR="$(pwd)/DESTDIR"
-        ( cd DESTDIR && find -ls )
-    - name: distcheck
-      run: |
-        make -C _build -j $(getconf _NPROCESSORS_ONLN) distcheck VERBOSE=1
-
   meson:
     name: Build with Meson and gcc, and test
     runs-on: ubuntu-20.04
@@ -103,7 +39,7 @@ jobs:
       run: mkdir test-logs
     - name: configure
       run: |
-        meson _build -Db_sanitize=address,undefined
+        meson _build
     - name: Build xdg-dbus-proxy
       run: ninja -C _build -v
     - name: Run tests
@@ -167,45 +103,38 @@ jobs:
       run: |
         sudo apt-get update
         sudo apt-get install -y \
-          autoconf \
-          autoconf-archive \
-          automake \
-          autopoint \
           clang \
           dbus \
           docbook-xml \
           docbook-xsl \
           libglib2.0-dev \
           libtool \
+          meson \
           xsltproc \
           ${NULL+}
     - name: Check out xdg-dbus-proxy
       uses: actions/checkout@v1
       with:
         submodules: true
-    - name: autoreconf
-      run: autoreconf -fi
+    - name: Create logs dir
+      run: mkdir test-logs
     - name: configure
-      run: ./configure
+      run: |
+        meson _build -Db_sanitize=address,undefined
       env:
         CC: clang
-        CFLAGS: >-
-          -O2
-          -Wp,-D_FORTIFY_SOURCE=2
-          -fsanitize=address
-          -fsanitize=undefined
     - name: Build xdg-dbus-proxy
-      run: make -j $(getconf _NPROCESSORS_ONLN) V=1
+      run: ninja -C _build -v
     - name: Perform CodeQL Analysis
       uses: github/codeql-action/analyze@v3
     - name: Run tests
-      run: make -j $(getconf _NPROCESSORS_ONLN) check VERBOSE=1
+      run: meson test -C _build -v
     - name: Collect overall test logs on failure
       if: failure()
-      run: mv test-suite.log test-logs/ || true
+      run: mv _build/meson-logs/testlog.txt test-logs/ || true
     - name: Collect individual test logs on cancel
       if: failure() || cancelled()
-      run: mv tests/*.log test-logs/ || true
+      run: mv _build/meson-logs/testlog.txt test-logs/ || true
     - name: Upload test logs
       uses: actions/upload-artifact@v1
       if: failure() || cancelled()
@@ -215,23 +144,20 @@ jobs:
 
   valgrind:
     name: Run tests in valgrind
-    needs: check # Don't run expensive test if main check fails
+    needs: meson # Don't run expensive test if main check fails
     runs-on: ubuntu-20.04 # Might as well test with a different one too
     steps:
     - name: Install Dependencies
       run: |
         sudo apt-get update
         sudo apt-get install -y \
-          autoconf \
-          autoconf-archive \
-          automake \
-          autopoint \
           clang \
           dbus \
           docbook-xml \
           docbook-xsl \
           libglib2.0-dev \
           libtool \
+          meson \
           valgrind \
           xsltproc \
           ${NULL+}
@@ -241,26 +167,23 @@ jobs:
         submodules: true
     - name: Create logs dir
       run: mkdir test-logs
-    - name: autoreconf
-      run: autoreconf -fi
     - name: configure
       run: |
-        mkdir _build
-        ( cd _build && ../configure )
+        meson _build
       env:
         CFLAGS: >-
           -O2
           -Wp,-D_FORTIFY_SOURCE=2
     - name: Build xdg-dbus-proxy
-      run: make -C _build -j $(getconf _NPROCESSORS_ONLN) V=1
+      run: ninja -C _build -v
     - name: Run tests
-      run: make -C _build -j $(getconf _NPROCESSORS_ONLN) check VERBOSE=1
+      run: meson test -C _build -v
     - name: Collect overall test logs on failure
       if: failure()
-      run: mv _build/test-suite.log test-logs/ || true
+      run: mv _build/meson-logs/testlog.txt test-logs/ || true
     - name: Collect individual test logs on cancel
       if: failure() || cancelled()
-      run: mv _build/tests/*.log test-logs/ || true
+      run: mv _build/meson-logs/testlog.txt test-logs/ || true
     - name: Upload test logs
       uses: actions/upload-artifact@v1
       if: failure() || cancelled()
